#!/bin/bash
#SBATCH -J my_job
#SBATCH --mail-user=felix.staniek@gmx.de
#SBATCH --mail-type=ALL
#SBATCH -e /home/ui31dymo/Lap1/errors/Job_Name.err.%j
#SBATCH -o /home/ui31dymo/Lap1/output/Job_Name.out.%j
#SBATCH --mem-per-cpu=1800
#SBATCH -t 00:03:00
#SBATCH -n 4
#SBATCH -p kurs1

echo "This is Job $SLURM_JOB_ID"
module load gcc
module load openmpi/gcc
cd ui31dymo/Lap1/SPP_Uebungen/source_praktikum_c/
make main
mpirun main

